version: '3'

services:
  env:
    build:
      context: ./env
      dockerfile: Dockerfile
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=development
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./env/dotfiles/.zshrc:/home/developer/.zshrc
      - ./env/dotfiles/.tmux.conf:/home/developer/.tmux.conf
      - ./env/dotfiles/.config/nvim/init.vim:/home/developer/.config/nvim/init.vim
      - ./env/dotfiles/.cache/dein/conf:/home/developer/.cache/dein/conf
      - ../myapp:/home/developer/work:cached
      - /home/developer/work/vendor
      - /home/developer/work/node_modules
      - /home/developer/work/tmp
      - /home/developer/work/log
      - /home/developer/work/.git
    networks: 
      - db-network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=development
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    networks: 
      - db-network

  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   tty: true
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DB_USER=root
  #     - DB_PASS=root
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #   volumes:
  #     - ../todo-vue:/app
  #   depends_on:
  #     - db
  #     - asset
  #   networks:
  #     - db-network
  #     - asset-network
  #   command: >
  #     bundle install --path vendor/bundle 

  # asset:
  #   build:
  #     context: ./asset
  #     dockerfile: Dockerfile
  #   tty: true
  #   ports:
  #     - "3035:3035"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ../todo-vue:/app
  #   networks:
  #     - asset-network
  #   command: >
  #     sh -c "yarn install; yarn run start"

volumes:
  db-data:

networks:
  db-network:
  asset-network:
